apiVersion: grafana.aws.m.upbound.io/v1beta1
kind: LicenseAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1beta1/licenseassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    licenseType: ENTERPRISE_FREE_TRIAL
    region: us-west-1
    workspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: grafana.aws.m.upbound.io/v1beta1
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1beta1/licenseassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    accountAccessType: CURRENT_ACCOUNT
    authenticationProviders:
    - SAML
    permissionType: SERVICE_MANAGED
    region: us-west-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: assume

---

apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1beta1/licenseassociation
  labels:
    testing.upbound.io/example-name: assume
  name: assume
  namespace: upbound-system
spec:
  forProvider:
    assumeRolePolicy: |-
      ${jsonencode({
          Version = "2012-10-17"
          Statement = [
            {
              Action = "sts:AssumeRole"
              Effect = "Allow"
              Sid    = ""
              Principal = {
                Service = "grafana.amazonaws.com"
              }
            },
          ]
        })}
    region: us-west-1
