# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../crds/cluster
  - ../crds/namespaced

patches:
- path: webhook.yaml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition

transformers:
  - splitter.yaml
