# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: networkfirewall.aws.upbound.io/v1beta2
kind: LoggingConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: networkfirewall/v1beta2/loggingconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    firewallArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    loggingConfiguration:
      logDestinationConfig:
      - logDestination:
          bucketName: ${aws_s3_bucket.example.bucket}
          prefix: example
        logDestinationType: S3
        logType: FLOW
    region: us-west-1
