# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: elasticbeanstalk.aws.m.upbound.io/v1beta1
kind: ConfigurationTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: elasticbeanstalk/v1beta1/configurationtemplate
  labels:
    testing.upbound.io/example-name: tf_template
  name: tf-template
  namespace: upbound-system
spec:
  forProvider:
    applicationSelector:
      matchLabels:
        testing.upbound.io/example-name: tftest
    region: us-west-1
    solutionStackName: 64bit Amazon Linux 2 v5.6.2 running Node.js 16
---
apiVersion: elasticbeanstalk.aws.m.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: elasticbeanstalk/v1beta1/application
  labels:
    testing.upbound.io/example-name: tftest
  name: first-app-test-qwerty-test
  namespace: upbound-system
spec:
  forProvider:
    appversionLifecycle:
      - deleteSourceFromS3: true
        maxCount: 128
        serviceRole: arn:aws:iam::153891904029:role/aws-elasticbeanstalk-service-role
    region: us-west-1
