apiVersion: configservice.aws.upbound.io/v1beta2
kind: ConfigurationRecorder
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta2/configurationrecorder
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    region: us-west-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: r

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta2/configurationrecorder
  labels:
    testing.upbound.io/example-name: r
  name: r
spec:
  forProvider:
    assumeRolePolicy: ${data.aws_iam_policy_document.assume_role.json}
    region: us-west-1
