# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: configservice.aws.upbound.io/v1beta2
kind: ConfigurationAggregator
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta2/configurationaggregator
  labels:
    testing.upbound.io/example-name: account
  name: account
spec:
  forProvider:
    accountAggregationSource:
      accountIds:
      - "123456789012"
      regions:
      - us-west-2
    region: us-west-1
