apiVersion: cloudfront.aws.m.upbound.io/v1beta1
kind: FieldLevelEncryptionConfig
metadata:
  annotations:
    meta.upbound.io/example-id: cloudfront/v1beta1/fieldlevelencryptionconfig
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    comment: test comment
    contentTypeProfileConfig:
    - contentTypeProfiles:
      - items:
        - contentType: application/x-www-form-urlencoded
          format: URLEncoded
      forwardWhenContentTypeIsUnknown: true
    queryArgProfileConfig:
    - forwardWhenQueryArgProfileIsUnknown: true
      queryArgProfiles:
      - items:
        - profileIdSelector:
            matchLabels:
              testing.upbound.io/example-name: test
          queryArg: Arg1
    region: us-west-1
