# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: route53.aws.upbound.io/v1beta1
kind: ResolverConfig
metadata:
  annotations:
    meta.upbound.io/example-id: route53/v1beta1/resolverconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    autodefinedReverseFlag: DISABLE
    region: us-west-1
    resourceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: route53/v1beta1/resolverconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    region: us-west-1
