# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: sagemaker.aws.upbound.io/v1beta1
kind: NotebookInstanceLifecycleConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: sagemaker/v1beta1/notebookinstancelifecycleconfiguration
  labels:
    testing.upbound.io/example-name: lc
  name: lc
spec:
  forProvider:
    onCreate: ${base64encode("echo foo")}
    onStart: ${base64encode("echo bar")}
    region: us-west-1
