apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: RealtimeLogConfig
metadata:
  labels:
    testing.upbound.io/example-name: realtimelogconfig
  name: example
spec:
  forProvider:
    endpoint:
      - kinesisStreamConfig:
          - roleArnSelector:
              matchLabels:
                testing.upbound.io/example-name: realtimelogconfig
            streamArnSelector:
              matchLabels:
                testing.upbound.io/example-name: realtimelogconfig
        streamType: Kinesis
    fields:
      - timestamp
      - c-ip
    name: example
    region: us-west-1
    samplingRate: 75
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  labels:
    testing.upbound.io/example-name: realtimelogconfig
  name: example
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": "sts:AssumeRole",
            "Principal": {
              "Service": "cloudfront.amazonaws.com"
            },
            "Effect": "Allow"
          }
        ]
      }
---
apiVersion: kinesis.aws.upbound.io/v1beta1
kind: Stream
metadata:
  name: example-op-0ix00uz1
  labels:
    testing.upbound.io/example-name: realtimelogconfig
spec:
  forProvider:
    region: us-west-1
    retentionPeriod: 48
    shardCount: 1
    shardLevelMetrics:
      - IncomingBytes
      - OutgoingBytes
    streamModeDetails:
      - streamMode: PROVISIONED
    tags:
      Environment: test
