apiVersion: cloudfront.aws.upbound.io/v1beta1
kind: RealtimeLogConfig
metadata:
  annotations:
    meta.upbound.io/example-id: cloudfront/v1beta1/realtimelogconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    endpoint:
    - kinesisStreamConfig:
      - roleArnSelector:
          matchLabels:
            testing.upbound.io/example-name: example
        streamArnSelector:
          matchLabels:
            testing.upbound.io/example-name: example
      streamType: Kinesis
    fields:
    - timestamp
    - c-ip
    name: example
    region: us-west-1
    samplingRate: 75

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: cloudfront/v1beta1/realtimelogconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    assumeRolePolicy: ${data.aws_iam_policy_document.assume_role.json}
