# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: apigateway.aws.upbound.io/v1beta2
kind: MethodSettings
metadata:
  annotations:
    meta.upbound.io/example-id: apigateway/v1beta2/methodsettings
  labels:
    testing.upbound.io/example-name: all
  name: all
spec:
  forProvider:
    methodPath: '*/*'
    region: us-west-1
    restApiIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    settings:
      loggingLevel: ERROR
      metricsEnabled: true
    stageNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Deployment
metadata:
  annotations:
    meta.upbound.io/example-id: apigateway/v1beta2/methodsettings
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
    restApiIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    triggers:
      redeployment: ${sha1(jsonencode(aws_api_gateway_rest_api.example.body))}

---

apiVersion: apigateway.aws.upbound.io/v1beta2
kind: RestAPI
metadata:
  annotations:
    meta.upbound.io/example-id: apigateway/v1beta2/methodsettings
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    body: |-
      ${jsonencode({
          openapi = "3.0.1"
          info = {
            title   = "example"
            version = "1.0"
          }
          paths = {
            "/path1" = {
              get = {
                x-amazon-apigateway-integration = {
                  httpMethod           = "GET"
                  payloadFormatVersion = "1.0"
                  type                 = "HTTP_PROXY"
                  uri                  = "https://ip-ranges.amazonaws.com/ip-ranges.json"
                }
              }
            }
          }
        })}
    name: example
    region: us-west-1

---

apiVersion: apigateway.aws.upbound.io/v1beta2
kind: Stage
metadata:
  annotations:
    meta.upbound.io/example-id: apigateway/v1beta2/methodsettings
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    deploymentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-west-1
    restApiIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    stageName: example
