apiVersion: lakeformation.aws.upbound.io/v1beta1
kind: DataLakeSettings
metadata:
  annotations:
    meta.upbound.io/example-id: lakeformation/v1beta1/datalakesettings
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    admins:
    - ${aws_iam_user.test.arn}
    - ${aws_iam_role.test.arn}
    region: us-west-1

---

