apiVersion: ecs.aws.m.upbound.io/v1beta1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/service
  labels:
    testing.upbound.io/example-name: mongo
  name: mongo
  namespace: upbound-system
spec:
  forProvider:
    clusterSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    desiredCount: 3
    iamRoleSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    loadBalancer:
    - containerName: mongo
      containerPort: 8080
      targetGroupArnSelector:
        matchLabels:
          testing.upbound.io/example-name: foo
    orderedPlacementStrategy:
    - field: cpu
      type: binpack
    placementConstraints:
    - expression: attribute:ecs.availability-zone in [us-west-2a, us-west-2b]
      type: memberOf
    region: us-west-1
    taskDefinitionSelector:
      matchLabels:
        testing.upbound.io/example-name: mongo
