apiVersion: appconfig.m.aws.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: appconfig/v1beta1/application
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Example AppConfig Application
    name: example-application-tf
    region: us-west-1
    tags:
      Type: AppConfig Application
