apiVersion: appconfig.aws.m.upbound.io/v1beta1
kind: DeploymentStrategy
metadata:
  annotations:
    meta.upbound.io/example-id: appconfig/v1beta1/deploymentstrategy
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    deploymentDurationInMinutes: 3
    description: Example Deployment Strategy
    finalBakeTimeInMinutes: 4
    growthFactor: 10
    growthType: LINEAR
    name: example-deployment-strategy-tf
    region: us-west-1
    replicateTo: NONE
    tags:
      Type: AppConfig Deployment Strategy
