apiVersion: s3.m.aws.upbound.io/v1beta1
kind: BucketRequestPaymentConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketrequestpaymentconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    payer: Requester
    region: us-west-1
