apiVersion: s3.m.aws.upbound.io/v1beta1
kind: BucketServerSideEncryptionConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketserversideencryptionconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: mybucket
    region: us-west-1
    rule:
    - applyServerSideEncryptionByDefault:
      - kmsMasterKeyIdSelector:
          matchLabels:
            testing.upbound.io/example-name: mykey
        sseAlgorithm: aws:kms

---

apiVersion: kms.m.aws.upbound.io/v1beta1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketserversideencryptionconfiguration
  labels:
    testing.upbound.io/example-name: mykey
  name: mykey
spec:
  forProvider:
    deletionWindowInDays: 10
    description: This key is used to encrypt bucket objects
    region: us-west-1

---

apiVersion: s3.m.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    meta.upbound.io/example-id: s3/v1beta1/bucketserversideencryptionconfiguration
  labels:
    testing.upbound.io/example-name: mybucket
  name: mybucket
spec:
  forProvider:
    region: us-west-1
