apiVersion: s3.m.aws.upbound.io/v1beta1
kind: BucketAnalyticsConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketanalyticsconfiguration
  labels:
    testing.upbound.io/example-name: example-entire-bucket
  name: example-entire-bucket
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: EntireBucket
    region: us-west-1
    storageClassAnalysis:
    - dataExport:
      - destination:
        - s3BucketDestination:
          - bucketArnSelector:
              matchLabels:
                testing.upbound.io/example-name: analytics

---

apiVersion: s3.m.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    meta.upbound.io/example-id: s3/v1beta1/bucketanalyticsconfiguration
  labels:
    testing.upbound.io/example-name: analytics
  name: analytics
spec:
  forProvider:
    region: us-west-1

---

apiVersion: s3.m.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    meta.upbound.io/example-id: s3/v1beta1/bucketanalyticsconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
