apiVersion: configservice.aws.upbound.io/v1beta1
kind: AWSConfigurationRecorderStatus
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/awsconfigurationrecorderstatus
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    isEnabled: true
    region: us-west-1

---

apiVersion: configservice.aws.upbound.io/v1beta2
kind: ConfigurationRecorder
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/awsconfigurationrecorderstatus
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    region: us-west-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: r

---

apiVersion: configservice.aws.upbound.io/v1beta2
kind: DeliveryChannel
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/awsconfigurationrecorderstatus
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    region: us-west-1
    s3BucketNameSelector:
      matchLabels:
        testing.upbound.io/example-name: b

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/awsconfigurationrecorderstatus
  labels:
    testing.upbound.io/example-name: r
  name: r
spec:
  forProvider:
    assumeRolePolicy: ${data.aws_iam_policy_document.assume_role.json}
    region: us-west-1

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/awsconfigurationrecorderstatus
  labels:
    testing.upbound.io/example-name: p
  name: p
spec:
  forProvider:
    policy: ${data.aws_iam_policy_document.p.json}
    region: us-west-1
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: r

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/awsconfigurationrecorderstatus
  labels:
    testing.upbound.io/example-name: a
  name: a
spec:
  forProvider:
    policyArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-west-1
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: r

---

apiVersion: s3.aws.upbound.io/v1beta2
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    meta.upbound.io/example-id: configservice/v1beta1/awsconfigurationrecorderstatus
  labels:
    testing.upbound.io/example-name: b
  name: b
spec:
  forProvider:
    region: us-west-1
