apiVersion: ecr.aws.upbound.io/v1alpha1
kind: ReplicationConfiguration
metadata:
  name: example
spec:
  forProvider:
    replicationConfiguration:
    - rule:
      - destination:
        - region: ${data.aws_regions.example.names[0]}
          registryId: ${data.aws_caller_identity.current.account_id}
  providerConfigRef:
    name: example
