# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: elasticbeanstalk.aws.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: elasticbeanstalk/v1beta1/application
  labels:
    testing.upbound.io/example-name: tftest
  name: first-app-test-qwerty-test
spec:
  forProvider:
    appversionLifecycle:
      - deleteSourceFromS3: true
        maxCount: 128
        serviceRole: arn:aws:iam::153891904029:role/aws-elasticbeanstalk-service-role
    region: us-east-2
