apiVersion: elasticbeanstalk.aws.m.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: elasticbeanstalk/v1beta1/application
  labels:
    testing.upbound.io/example-name: tftest
  name: tftest
  namespace: upbound-system
spec:
  forProvider:
    appversionLifecycle:
    - deleteSourceFromS3: true
      maxCount: 128
      serviceRoleSelector:
        matchLabels:
          testing.upbound.io/example-name: beanstalk_service
    description: tf-test-desc
    region: us-west-1
