apiVersion: appconfig.aws.upbound.io/v1alpha1
kind: Deployment
metadata:
  name: example
spec:
  forProvider:
    applicationId: ${aws_appconfig_application.example.id}
    configurationProfileId: ${aws_appconfig_configuration_profile.example.configuration_profile_id}
    configurationVersion: ${aws_appconfig_hosted_configuration_version.example.version_number}
    deploymentStrategyId: ${aws_appconfig_deployment_strategy.example.id}
    description: My example deployment
    environmentId: ${aws_appconfig_environment.example.environment_id}
    tags:
      Type: AppConfig Deployment
  providerConfigRef:
    name: example
