apiVersion: appconfig.aws.upbound.io/v1alpha1
kind: Environment
metadata:
  name: example
spec:
  forProvider:
    applicationId: ${aws_appconfig_application.example.id}
    description: Example AppConfig Environment
    monitor:
    - alarmArn: ${aws_cloudwatch_metric_alarm.example.arn}
      alarmRoleArn: ${aws_iam_role.example.arn}
    name: example-environment-tf
    tags:
      Type: AppConfig Environment
  providerConfigRef:
    name: example
