apiVersion: glue.aws.upbound.io/v1alpha1
kind: SecurityConfiguration
metadata:
  name: example
spec:
  forProvider:
    encryptionConfiguration:
    - cloudwatchEncryption:
      - cloudwatchEncryptionMode: DISABLED
      jobBookmarksEncryption:
      - jobBookmarksEncryptionMode: DISABLED
      s3Encryption:
      - kmsKeyArn: ${data.aws_kms_key.example.arn}
        s3EncryptionMode: SSE-KMS
  providerConfigRef:
    name: example
