# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: ivs.aws.upbound.io/v1beta2
kind: RecordingConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: ivs/v1beta2/recordingconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    destinationConfiguration:
      s3:
        bucketName: ivs-stream-archive
    name: recording_configuration-1
    region: us-west-1
