apiVersion: elasticbeanstalk.aws.upbound.io/v1alpha1
kind: Environment
metadata:
  name: example
spec:
  forProvider:
    application: tf-test-name
    name: tf-test-name
    solutionStackName: 64bit Amazon Linux 2015.03 v2.0.3 running Go 1.4
  providerConfigRef:
    name: example
