# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: cloud9.aws.upbound.io/v1beta1
kind: EnvironmentEC2
metadata:
  annotations:
    meta.upbound.io/example-id: cloud9/v1beta1/environmentec2
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    imageId: amazonlinux-2023-x86_64
    instanceType: t2.micro
    name: example-env
    region: us-west-1
