apiVersion: kafka.aws.upbound.io/v1beta1
kind: Configuration
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    kafkaVersions:
    - 2.1.0
    name: example
    region: us-west-1
    serverProperties: |
      auto.create.topics.enable = true
      delete.topic.enable = true

---

