# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apprunner.aws.m.upbound.io/v1beta1
kind: ObservabilityConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: apprunner/v1beta1/observabilityconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    observabilityConfigurationName: example
    region: us-east-1
    tags:
      Name: example-apprunner-observability-configuration
    traceConfiguration:
      vendor: AWSXRAY
