# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: deploy.aws.upbound.io/v1beta1
kind: App
metadata:
  annotations:
    meta.upbound.io/example-id: deploy/v1beta1/app
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    computePlatform: ECS
    region: us-east-2
