# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: appconfig.aws.upbound.io/v1beta1
kind: Environment
metadata:
  annotations:
    meta.upbound.io/example-id: appconfig/v1beta1/environment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: Example AppConfig Environment
    monitor:
    - alarmArnSelector:
        matchLabels:
          testing.upbound.io/example-name: foobar
      alarmRoleArnSelector:
        matchLabels:
          testing.upbound.io/example-name: role
    name: example-environment-tf
    region: us-east-2
    tags:
      Type: AppConfig Environment
---
apiVersion: appconfig.aws.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: appconfig/v1beta1/environment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Example AppConfig Application
    name: example-application-tf
    region: us-east-2
    tags:
      Type: AppConfig Application
---
apiVersion: cloudwatch.aws.upbound.io/v1beta1
kind: MetricAlarm
metadata:
  annotations:
    meta.upbound.io/example-id: cloudwatch/v1beta1/metricalarm
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    alarmDescription: This metric monitors ec2 cpu utilization
    comparisonOperator: GreaterThanOrEqualToThreshold
    evaluationPeriods: 2
    insufficientDataActions: []
    metricName: CPUUtilization
    namespace: AWS/EC2
    period: 120
    region: us-east-2
    statistic: Average
    threshold: 80
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: sample-role
  labels:
    testing.upbound.io/example-name: role
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "eks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: sample-policy-attachment
  labels:
    testing.upbound.io/example-name: role
spec:
  forProvider:
    policyArnSelector:
      matchLabels:
        testing.upbound.io/example-name: role
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: role
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: sample-user-policy
  labels:
    testing.upbound.io/example-name: role
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
              "Sid": "VisualEditor0",
              "Effect": "Allow",
              "Action": "elastic-inference:Connect",
              "Resource": "*"
          }
        ]
      }
