apiVersion: lambda.aws.upbound.io/v1beta1
kind: FunctionEventInvokeConfig
metadata:
  annotations:
    meta.upbound.io/example-id: lambda/v1beta1/functioneventinvokeconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    destinationConfig:
    - onFailure:
      - destinationSelector:
          matchLabels:
            testing.upbound.io/example-name: example
      onSuccess:
      - destinationSelector:
          matchLabels:
            testing.upbound.io/example-name: example
    functionName: ${aws_lambda_alias.example.function_name}
    region: us-west-1

---

