# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: iot.aws.upbound.io/v1beta2
kind: IndexingConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: iot/v1beta2/indexingconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
    thingIndexingConfiguration:
      customField:
      - name: shadow.desired.power
        type: Boolean
      - name: attributes.version
        type: Number
      - name: shadow.name.thing1shadow.desired.DefaultDesired
        type: String
      - name: deviceDefender.securityProfile1.NUMBER_VALUE_BEHAVIOR.lastViolationValue.number
        type: Number
      deviceDefenderIndexingMode: VIOLATIONS
      filter:
        namedShadowNames:
        - thing1shadow
      namedShadowIndexingMode: "ON"
      thingConnectivityIndexingMode: STATUS
      thingIndexingMode: REGISTRY_AND_SHADOW
