apiVersion: autoscaling.aws.upbound.io/v1beta1
kind: LaunchConfiguration
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "This resource refers to an AMI ID."
    meta.upbound.io/example-id: autoscaling/v1beta1/launchconfiguration
  labels:
    testing.upbound.io/example-name: as_conf
  name: as-conf
spec:
  forProvider:
    imageId: ${data.aws_ami.ubuntu.id}
    instanceType: t2.micro
    region: us-west-1
