# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: eks.aws.upbound.io/v1beta1
kind: IdentityProviderConfig
metadata:
  annotations:
    uptest.upbound.io/timeout: "3600" # one hour timeout
  name: example
spec:
  forProvider:
    region: us-east-2
    clusterName: test
    oidc:
    - clientId: test-audience
      issuerUrl: https://issuer.url
