apiVersion: kinesisanalytics.aws.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: kinesisanalytics/v1beta1/application
  labels:
    testing.upbound.io/example-name: test_application
  name: test-application
spec:
  forProvider:
    inputs:
    - kinesisStream:
      - resourceArnSelector:
          matchLabels:
            testing.upbound.io/example-name: test_stream
        roleArnSelector:
          matchLabels:
            testing.upbound.io/example-name: test
      namePrefix: test_prefix
      parallelism:
      - count: 1
      schema:
      - recordColumns:
        - mapping: $.test
          name: test
          sqlType: VARCHAR(8)
        recordEncoding: UTF-8
        recordFormat:
        - mappingParameters:
          - json:
            - recordRowPath: $
    region: us-west-1

---

apiVersion: kinesis.aws.upbound.io/v1beta1
kind: Stream
metadata:
  annotations:
    meta.upbound.io/example-id: kinesisanalytics/v1beta1/application
  labels:
    testing.upbound.io/example-name: test_stream
  name: test-stream
spec:
  forProvider:
    region: us-west-1
    shardCount: 1

---

