apiVersion: kinesisanalytics.aws.upbound.io/v1alpha1
kind: Application
metadata:
  name: example
spec:
  forProvider:
    inputs:
    - kinesisStream:
      - resourceArn: ${aws_kinesis_stream.test_stream.arn}
        roleArn: ${aws_iam_role.test.arn}
      namePrefix: test_prefix
      parallelism:
      - count: 1
      schema:
      - recordColumns:
        - mapping: $.test
          name: test
          sqlType: VARCHAR(8)
        recordEncoding: UTF-8
        recordFormat:
        - mappingParameters:
          - json:
            - recordRowPath: $
    name: kinesis-analytics-application-test
  providerConfigRef:
    name: example
