apiVersion: glue.aws.upbound.io/v1alpha1
kind: DataCatalogEncryptionSettings
metadata:
  name: example
spec:
  forProvider:
    dataCatalogEncryptionSettings:
    - connectionPasswordEncryption:
      - awsKmsKeyId: ${aws_kms_key.test.arn}
        returnConnectionPasswordEncrypted: true
      encryptionAtRest:
      - catalogEncryptionMode: SSE-KMS
        sseAwsKmsKeyId: ${aws_kms_key.test.arn}
  providerConfigRef:
    name: example
