apiVersion: glue.aws.upbound.io/v1beta1
kind: DataCatalogEncryptionSettings
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dataCatalogEncryptionSettings:
    - connectionPasswordEncryption:
      - awsKmsKeyIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test
        returnConnectionPasswordEncrypted: true
      encryptionAtRest:
      - catalogEncryptionMode: SSE-KMS
        sseAwsKmsKeyIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test
    region: us-west-1

---

