apiVersion: emr.aws.upbound.io/v1alpha1
kind: SecurityConfiguration
metadata:
  name: example
spec:
  forProvider:
    configuration: |
      {
        "EncryptionConfiguration": {
          "AtRestEncryptionConfiguration": {
            "S3EncryptionConfiguration": {
              "EncryptionMode": "SSE-S3"
            },
            "LocalDiskEncryptionConfiguration": {
              "EncryptionKeyProviderType": "AwsKms",
              "AwsKmsKey": "arn:aws:kms:us-west-2:187416307283:alias/tf_emr_test_key"
            }
          },
          "EnableInTransitEncryption": false,
          "EnableAtRestEncryption": true
        }
      }
    name: emrsc_other
  providerConfigRef:
    name: example
