apiVersion: imagebuilder.aws.upbound.io/v1alpha1
kind: InfrastructureConfiguration
metadata:
  name: example
spec:
  forProvider:
    description: example description
    instanceProfileName: ${aws_iam_instance_profile.example.name}
    instanceTypes:
    - t2.nano
    - t3.micro
    keyPair: ${aws_key_pair.example.key_name}
    logging:
    - s3Logs:
      - s3BucketName: ${aws_s3_bucket.example.bucket}
        s3KeyPrefix: logs
    name: example
    securityGroupIdRefs:
    - name: example
    snsTopicArn: ${aws_sns_topic.example.arn}
    subnetIdRef:
      name: example
    tags:
      foo: bar
    terminateInstanceOnFailure: true
  providerConfigRef:
    name: example
