# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: route53resolver.aws.m.upbound.io/v1beta1
kind: QueryLogConfig
metadata:
  annotations:
    meta.upbound.io/example-id: route53resolver/v1beta1/querylogconfig
  labels:
    testing.upbound.io/example-name: example-querylogconfig
  name: example-querylogconfig
  namespace: upbound-system
spec:
  forProvider:
    destinationArn: arn:aws:s3:::example-querylogconfig-bucket
    name: example-querylogconfig
    region: us-west-1
    tags:
      Environment: test
---
apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: route53resolver/v1beta1/querylogconfig
  labels:
    testing.upbound.io/example-name: example-querylogconfig
  name: example-querylogconfig-bucket
  namespace: upbound-system
spec:
  forProvider:
    region: us-west-1
    tags:
      Name: QueryLogBucket