apiVersion: ecr.aws.m.upbound.io/v1beta1
kind: RegistryScanningConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: ecr/v1beta1/registryscanningconfiguration
  labels:
    testing.upbound.io/example-name: configuration
  name: configuration
spec:
  forProvider:
    region: us-west-1
    rule:
    - repositoryFilter:
      - filter: example
        filterType: WILDCARD
      scanFrequency: CONTINUOUS_SCAN
    scanType: ENHANCED
