# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: s3control.aws.m.upbound.io/v1beta1
kind: StorageLensConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3control/v1beta1/storagelensconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: slcexample
spec:
  forProvider:
    configId: example-1
    region: us-west-1
    storageLensConfiguration:
      accountLevel:
        activityMetrics:
          enabled: true
        bucketLevel:
          activityMetrics:
            enabled: true
      enabled: false
