# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: appconfig.aws.m.upbound.io/v1beta1
kind: Deployment
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Requires configuration version to replaced manually."
    meta.upbound.io/example-id: appconfig/v1beta1/deployment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    configurationProfileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    deploymentStrategyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: My example deployment
    configurationVersion: "1" #manually add version for the created hosted configuration version
    environmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-east-1
    tags:
      Type: AppConfig Deployment
---
apiVersion: appconfig.aws.m.upbound.io/v1beta1
kind: HostedConfigurationVersion
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Requires configuration version to replaced manually."
    meta.upbound.io/example-id: appconfig/v1beta1/deployment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    configurationProfileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    contentSecretRef:
      key: example-key
      name: example-secret
    contentType: application/json
    description: Example Freeform Hosted Configuration Version
    region: us-east-1
---
apiVersion: appconfig.aws.m.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Requires configuration version to replaced manually."
    meta.upbound.io/example-id: appconfig/v1beta1/deployment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Example AppConfig Application
    name: example-application-tf
    region: us-east-1
    tags:
      Type: AppConfig Application
---
apiVersion: appconfig.aws.m.upbound.io/v1beta1
kind: ConfigurationProfile
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Requires configuration version to replaced manually."
    meta.upbound.io/example-id: appconfig/v1beta1/deployment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: Example Configuration Profile
    locationUri: hosted
    name: example-configuration-profile-tf
    region: us-east-1
    tags:
      Type: AppConfig Configuration Profile
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
stringData:
  example-key: "{\"foo\":\"bar\",\"fruit\":[\"apple\",\"pear\",\"orange\"],\"isThingEnabled\":true,\"version\":\"1\"}"
---
apiVersion: appconfig.aws.m.upbound.io/v1beta1
kind: DeploymentStrategy
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Requires configuration version to replaced manually."
    meta.upbound.io/example-id: appconfig/v1beta1/deployment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    deploymentDurationInMinutes: 3
    description: Example Deployment Strategy
    finalBakeTimeInMinutes: 4
    growthFactor: 10
    growthType: LINEAR
    name: example-deployment-strategy-tf
    region: us-east-1
    replicateTo: NONE
    tags:
      Type: AppConfig Deployment Strategy
---
apiVersion: appconfig.aws.m.upbound.io/v1beta1
kind: Environment
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Requires configuration version to replaced manually."
    meta.upbound.io/example-id: appconfig/v1beta1/deployment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: Example AppConfig Environment
    name: example-environment-tf
    region: us-east-1
    tags:
      Type: AppConfig Environment
