# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: appconfig.aws.m.upbound.io/v1beta1
kind: HostedConfigurationVersion
metadata:
  annotations:
    meta.upbound.io/example-id: appconfig/v1beta1/hostedconfigurationversion
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    configurationProfileIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    contentSecretRef:
      key: example-key
      name: example-secret
    contentType: application/json
    description: Example Freeform Hosted Configuration Version
    region: us-west-1
---
apiVersion: appconfig.aws.m.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: appconfig/v1beta1/hostedconfigurationversion
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Example AppConfig Application
    name: example-application-tf
    region: us-west-1
    tags:
      Type: AppConfig Application
---
apiVersion: appconfig.aws.m.upbound.io/v1beta1
kind: ConfigurationProfile
metadata:
  annotations:
    meta.upbound.io/example-id: appconfig/v1beta1/hostedconfigurationversion
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: Example Configuration Profile
    locationUri: hosted
    name: example-configuration-profile-tf
    region: us-west-1
    tags:
      Type: AppConfig Configuration Profile
---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: upbound-system
type: Opaque
stringData:
  example-key: "{\"foo\":\"bar\",\"fruit\":[\"apple\",\"pear\",\"orange\"],\"isThingEnabled\":true}"
