# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: configservice.aws.m.upbound.io/v1beta1
kind: ConfigRule
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/configrule
  labels:
    testing.upbound.io/example-name: r
  name: this
spec:
  forProvider:
    region: us-west-1
    source:
      owner: AWS
      sourceIdentifier: S3_BUCKET_VERSIONING_ENABLED
---
apiVersion: configservice.aws.m.upbound.io/v1beta1
kind: ConfigurationRecorder
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/configrule
  labels:
    testing.upbound.io/example-name: foo
  name: example-recorder
spec:
  forProvider:
    region: us-west-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: r
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/configrule
  labels:
    testing.upbound.io/example-name: r
  name: test-role
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": "sts:AssumeRole",
            "Principal": {
              "Service": "config.amazonaws.com"
            },
            "Effect": "Allow",
            "Sid": ""
          }
        ]
      }
