# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: cloud9.aws.upbound.io/v1beta1
kind: EnvironmentMembership
metadata:
  annotations:
    meta.upbound.io/example-id: cloud9/v1beta1/environmentmembership
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    environmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    permissions: read-only
    region: us-west-1
    userArnSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: cloud9.aws.upbound.io/v1beta1
kind: EnvironmentEC2
metadata:
  annotations:
    meta.upbound.io/example-id: cloud9/v1beta1/environmentmembership
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    instanceType: t2.micro
    name: some-env
    region: us-west-1

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: cloud9/v1beta1/environmentmembership
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    region: us-west-1
