# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: s3control.aws.upbound.io/v1beta1
kind: StorageLensConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3control/v1beta1/storagelensconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: slcexample
spec:
  forProvider:
    configId: example-1
    region: us-east-2
    storageLensConfiguration:
    - accountLevel:
      - activityMetrics:
        - enabled: true
        bucketLevel:
        - activityMetrics:
          - enabled: true
      enabled: false
