# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: route53resolver.aws.m.upbound.io/v1beta1
kind: QueryLogConfig
metadata:
  annotations:
    meta.upbound.io/example-id: route53resolver/v1beta1/querylogconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    destinationArn: ${aws_s3_bucket.example.arn}
    name: example
    region: us-west-1
    tags:
      Environment: Prod
