# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: s3.aws.m.upbound.io/v1beta1
kind: BucketIntelligentTieringConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketintelligenttieringconfiguration
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: s3
    name: EntireBucket
    region: us-west-1
    tiering:
      - accessTier: DEEP_ARCHIVE_ACCESS
        days: 180
      - accessTier: ARCHIVE_ACCESS
        days: 125
