# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: s3.aws.m.upbound.io/v1beta1
kind: BucketAnalyticsConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketanalyticsconfiguration
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: s3
    name: EntireBucket
    region: us-west-1
    storageClassAnalysis:
      dataExport:
        destination:
          s3BucketDestination:
            bucketArnSelector:
              matchLabels:
                testing.upbound.io/example-name: s3
