# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: s3.aws.m.upbound.io/v1beta1
kind: BucketRequestPaymentConfiguration
metadata:
  name: example
  namespace: upbound-system
spec:
  forProvider:
    region: us-west-1
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: s3
    payer: Requester
