apiVersion: configservice.aws.m.upbound.io/v1beta1
kind: ConfigRule
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/configrule
  labels:
    testing.upbound.io/example-name: r
  name: r
spec:
  forProvider:
    region: us-west-1
    source:
    - owner: AWS
      sourceIdentifierSelector:
        matchLabels:
          testing.upbound.io/example-name: example

---

apiVersion: configservice.aws.m.upbound.io/v1beta1
kind: ConfigurationRecorder
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/configrule
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    region: us-west-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: r

---

apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/configrule
  labels:
    testing.upbound.io/example-name: r
  name: r
spec:
  forProvider:
    assumeRolePolicy: ${data.aws_iam_policy_document.assume_role.json}

---

apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicy
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/configrule
  labels:
    testing.upbound.io/example-name: p
  name: p
spec:
  forProvider:
    policy: ${data.aws_iam_policy_document.p.json}
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: r
