apiVersion: configservice.m.aws.upbound.io/v1beta1
kind: RemediationConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/remediationconfiguration
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    automatic: true
    executionControls:
    - ssmControls:
      - concurrentExecutionRatePercentage: 25
        errorPercentage: 20
    maximumAutomaticAttempts: 10
    parameter:
    - name: AutomationAssumeRole
      staticValue: arn:aws:iam::875924563244:role/security_config
    - name: BucketName
      resourceValue: RESOURCE_ID
    - name: SSEAlgorithm
      staticValue: AES256
    region: us-west-1
    resourceType: AWS::S3::Bucket
    retryAttemptSeconds: 600
    targetId: AWS-EnableS3BucketEncryption
    targetType: SSM_DOCUMENT
    targetVersion: "1"

---

apiVersion: configservice.m.aws.upbound.io/v1beta1
kind: ConfigRule
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/remediationconfiguration
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    region: us-west-1
    source:
    - owner: AWS
      sourceIdentifierSelector:
        matchLabels:
          testing.upbound.io/example-name: example
