# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: lambda.aws.upbound.io/v1beta1
kind: ProvisionedConcurrencyConfig
metadata:
  annotations:
    meta.upbound.io/example-id: lambda/v1beta1/provisionedconcurrencyconfig
    upjet.upbound.io/manual-intervention: "This resource requires a valid function name or ARN."
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-east-2
    functionName: example
    provisionedConcurrentExecutions: 1
    qualifier: "1"
