# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: xray.aws.upbound.io/v1beta1
kind: EncryptionConfig
metadata:
  annotations:
    meta.upbound.io/example-id: xray/v1beta1/encryptionconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
    type: NONE
