# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: efs.aws.m.upbound.io/v1beta1
kind: ReplicationConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: efs/v1beta1/replicationconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: replicationconfig
spec:
  forProvider:
    destination:
      region: us-west-2
    region: us-west-1
    sourceFileSystemIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
---
apiVersion: efs.aws.m.upbound.io/v1beta1
kind: FileSystem
metadata:
  annotations:
    meta.upbound.io/example-id: efs/v1beta1/replicationconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: filesystem
spec:
  forProvider:
    region: us-west-1
