apiVersion: ecs.aws.upbound.io/v1beta1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/service
  labels:
    testing.upbound.io/example-name: mongo
  name: mongo
spec:
  forProvider:
    clusterSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    desiredCount: 3
    iamRoleSelector:
      matchLabels:
        testing.upbound.io/example-name: foo
    loadBalancer:
    - containerName: mongo
      containerPort: 8080
      targetGroupArn: ${aws_lb_target_group.foo.arn}
    orderedPlacementStrategy:
    - field: cpu
      type: binpack
    placementConstraints:
    - expression: attribute:ecs.availability-zone in [us-west-2a, us-west-2b]
      type: memberOf
    region: us-west-1
    taskDefinition: ${aws_ecs_task_definition.mongo.arn}

---

