apiVersion: sagemaker.aws.m.upbound.io/v1beta1
kind: AppImageConfig
metadata:
  annotations:
    meta.upbound.io/example-id: sagemaker/v1beta1/appimageconfig
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    kernelGatewayImageConfig:
    - kernelSpec:
      - name: example
    region: us-west-1
