apiVersion: servicediscovery.m.aws.upbound.io/v1beta1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: servicediscovery/v1beta1/service
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dnsConfig:
    - dnsRecords:
      - ttl: 10
        type: A
      namespaceIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      routingPolicy: MULTIVALUE
    healthCheckCustomConfig:
    - failureThreshold: 1
    name: example
    region: us-west-1

---

apiVersion: servicediscovery.m.aws.upbound.io/v1beta1
kind: PrivateDNSNamespace
metadata:
  annotations:
    meta.upbound.io/example-id: servicediscovery/v1beta1/service
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: example
    name: example.terraform.local
    region: us-west-1
    vpcSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: ec2.m.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: servicediscovery/v1beta1/service
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    region: us-west-1
