apiVersion: deploy.aws.m.upbound.io/v1beta1
kind: DeploymentConfig
metadata:
  annotations:
    meta.upbound.io/example-id: deploy/v1beta1/deploymentconfig
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    minimumHealthyHosts:
    - type: HOST_COUNT
      value: 2
    region: us-west-1

---

apiVersion: deploy.aws.m.upbound.io/v1beta1
kind: DeploymentGroup
metadata:
  annotations:
    meta.upbound.io/example-id: deploy/v1beta1/deploymentconfig
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: upbound-system
spec:
  forProvider:
    alarmConfiguration:
    - alarms:
      - my-alarm-name
      enabled: true
    appNameSelector:
      matchLabels:
        testing.upbound.io/example-name: foo_app
    autoRollbackConfiguration:
    - enabled: true
      events:
      - DEPLOYMENT_FAILURE
    deploymentConfigName: ${aws_codedeploy_deployment_config.foo.id}
    ec2TagFilter:
    - key: filterkey
      type: KEY_AND_VALUE
      value: filtervalue
    region: us-west-1
    serviceRoleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: foo_role
    triggerConfiguration:
    - triggerEvents:
      - DeploymentFailure
      triggerName: foo-trigger
      triggerTargetArnSelector:
        matchLabels:
          testing.upbound.io/example-name: example
