apiVersion: deploy.aws.m.upbound.io/v1beta1
kind: DeploymentGroup
metadata:
  annotations:
    meta.upbound.io/example-id: deploy/v1beta1/deploymentgroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    alarmConfiguration:
    - alarms:
      - my-alarm-name
      enabled: true
    appNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    autoRollbackConfiguration:
    - enabled: true
      events:
      - DEPLOYMENT_FAILURE
    ec2TagSet:
    - ec2TagFilter:
      - key: filterkey1
        type: KEY_AND_VALUE
        value: filtervalue
      - key: filterkey2
        type: KEY_AND_VALUE
        value: filtervalue
    outdatedInstancesStrategy: UPDATE
    region: us-west-1
    serviceRoleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    triggerConfiguration:
    - triggerEvents:
      - DeploymentFailure
      triggerName: example-trigger
      triggerTargetArnSelector:
        matchLabels:
          testing.upbound.io/example-name: example

---

apiVersion: deploy.aws.m.upbound.io/v1beta1
kind: App
metadata:
  annotations:
    meta.upbound.io/example-id: deploy/v1beta1/deploymentgroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1

---

apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: deploy/v1beta1/deploymentgroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    assumeRolePolicy: ${data.aws_iam_policy_document.assume_role.json}

---

apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: deploy/v1beta1/deploymentgroup
  labels:
    testing.upbound.io/example-name: AWSCodeDeployRole
  name: awscodedeployrole
spec:
  forProvider:
    policyArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: sns.aws.m.upbound.io/v1beta1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: deploy/v1beta1/deploymentgroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
