apiVersion: efs.m.aws.upbound.io/v1beta1
kind: ReplicationConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: efs/v1beta1/replicationconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    destination:
    - region: us-west-2
    region: us-west-1
    sourceFileSystemIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: efs.m.aws.upbound.io/v1beta1
kind: FileSystem
metadata:
  annotations:
    meta.upbound.io/example-id: efs/v1beta1/replicationconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1
