apiVersion: glue.aws.m.upbound.io/v1beta1
kind: SecurityConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: glue/v1beta1/securityconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    encryptionConfiguration:
    - cloudwatchEncryption:
      - cloudwatchEncryptionMode: DISABLED
      jobBookmarksEncryption:
      - jobBookmarksEncryptionMode: DISABLED
      s3Encryption:
      - kmsKeyArnSelector:
          matchLabels:
            testing.upbound.io/example-name: aws_kms_key
        s3EncryptionMode: SSE-KMS
    region: us-west-1
