# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: amp.aws.upbound.io/v1beta1
kind: AlertManagerDefinition
metadata:
  annotations:
    meta.upbound.io/example-id: amp/v1beta1/alertmanagerdefinition
  labels:
    testing.upbound.io/example-name: demo
  name: demo
spec:
  forProvider:
    definition: |
      alertmanager_config: |
        route:
          receiver: 'default'
        receivers:
          - name: 'default'
    region: us-west-1
    workspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: demo

---

apiVersion: amp.aws.upbound.io/v1beta2
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: amp/v1beta1/alertmanagerdefinition
  labels:
    testing.upbound.io/example-name: demo
  name: demo
spec:
  forProvider:
    region: us-west-1
