apiVersion: wafv2.aws.upbound.io/v1alpha1
kind: WebACLLoggingConfiguration
metadata:
  name: example
spec:
  forProvider:
    logDestinationConfigs:
    - ${aws_kinesis_firehose_delivery_stream.example.arn}
    redactedFields:
    - singleHeader:
      - name: user-agent
    resourceArn: ${aws_wafv2_web_acl.example.arn}
  providerConfigRef:
    name: example
