apiVersion: opsworks.aws.upbound.io/v1alpha1
kind: Application
metadata:
  name: example
spec:
  forProvider:
    appSource:
    - revision: master
      type: git
      url: https://github.com/example.git
    autoBundleOnDeploy: true
    description: This is a Rails application
    documentRoot: public
    domains:
    - example.com
    - sub.example.com
    enableSsl: true
    environment:
    - key: key
      secure: false
      value: value
    name: foobar application
    railsEnv: staging
    shortName: foobar
    sslConfiguration:
    - certificate: ${file("./foobar.crt")}
      privateKeySecretRef:
        key: attribute.foobar.key
        name: example-secret
        namespace: crossplane-system
    stackId: ${aws_opsworks_stack.main.id}
    type: rails
  providerConfigRef:
    name: example
