apiVersion: apprunner.aws.upbound.io/v1beta1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: apprunner/v1beta1/service
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    networkConfiguration:
    - egressConfiguration:
      - egressType: VPC
        vpcConnectorArnSelector:
          matchLabels:
            testing.upbound.io/example-name: connector
    region: us-west-1
    serviceName: example
    sourceConfiguration:
    - authenticationConfiguration:
      - connectionArnSelector:
          matchLabels:
            testing.upbound.io/example-name: example
      codeRepository:
      - codeConfiguration:
        - codeConfigurationValues:
          - buildCommand: python setup.py develop
            port: "8000"
            runtime: PYTHON_3
            startCommand: python runapp.py
          configurationSource: API
        repositoryUrl: https://github.com/example/my-example-python-app
        sourceCodeVersion:
        - type: BRANCH
          value: main
    tags:
      Name: example-apprunner-service

---

