# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: sagemaker.aws.m.upbound.io/v1beta1
kind: StudioLifecycleConfig
metadata:
  annotations:
    meta.upbound.io/example-id: sagemaker/v1beta1/studiolifecycleconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    region: us-west-1
    studioLifecycleConfigAppType: JupyterServer
    studioLifecycleConfigContent: ${base64encode("echo Hello")}
