# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: mq.aws.upbound.io/v1beta1
kind: Configuration
metadata:
  annotations:
    meta.upbound.io/example-id: mq/v1beta1/configuration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    data: |
      <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
      <broker xmlns="http://activemq.apache.org/schema/core">
        <plugins>
          <forcePersistencyModeBrokerPlugin persistenceFlag="true"/>
          <statisticsBrokerPlugin/>
          <timeStampingBrokerPlugin ttlCeiling="86400000" zeroExpirationOverride="86400000"/>
        </plugins>
      </broker>
    description: Example Configuration
    engineType: ActiveMQ
    engineVersion: 5.17.6
    name: example
    region: us-west-1
