# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: kafka.aws.upbound.io/v1beta1
kind: Configuration
metadata:
  name: example
spec:
  forProvider:
    kafkaVersions:
    - 2.1.0
    name: example
    region: us-east-2
    serverProperties: |
      auto.create.topics.enable = true
      delete.topic.enable = true
