# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: redshift.aws.upbound.io/v1beta1
kind: HSMConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: redshift/v1beta1/hsmconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: example
    hsmIpAddress: 10.0.0.1
    hsmPartitionName: aws
    hsmPartitionPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    hsmServerPublicCertificate: example
    region: us-west-1
