# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: amplify.aws.m.upbound.io/v1beta1
kind: BackendEnvironment
metadata:
  annotations:
    meta.upbound.io/example-id: amplify/v1beta1/backendenvironment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    appIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    deploymentArtifacts: app-example-deployment
    region: us-west-1
    stackName: amplify-app-example
---
apiVersion: amplify.aws.m.upbound.io/v1beta1
kind: App
metadata:
  annotations:
    meta.upbound.io/example-id: amplify/v1beta1/backendenvironment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example
    region: us-west-1
