apiVersion: apigatewayv2.m.aws.upbound.io/v1beta1
kind: Deployment
metadata:
  annotations:
    meta.upbound.io/example-id: apigatewayv2/v1beta1/deployment
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    apiIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    description: Example deployment
    region: us-west-1
