apiVersion: sns.aws.upbound.io/v1alpha1
kind: PlatformApplication
metadata:
  name: example
spec:
  forProvider:
    name: apns_application
    platform: APNS
    platformCredentialSecretRef:
      key: example-key
      name: example-secret
      namespace: crossplane-system
    platformPrincipalSecretRef:
      key: example-key
      name: example-secret
      namespace: crossplane-system
  providerConfigRef:
    name: example
