# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: sns.aws.upbound.io/v1beta1
kind: PlatformApplication
metadata:
  annotations:
    meta.upbound.io/example-id: sns/v1beta1/platformapplication
  labels:
    testing.upbound.io/example-name: apns_application
  name: apns-application
spec:
  forProvider:
    platform: APNS
    platformCredentialSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    platformPrincipalSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    region: us-west-1
