apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketCorsConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketcorsconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    corsRule:
    - allowedHeaders:
      - '*'
      allowedMethods:
      - PUT
      - POST
      allowedOrigins:
      - https://s3-website-test.hashicorp.com
      exposeHeaders:
      - ETag
      maxAgeSeconds: 3000
    - allowedMethods:
      - GET
      allowedOrigins:
      - '*'
    region: us-west-1

---

apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-west-1

---

