apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketObjectLockConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketobjectlockconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-west-1
    rule:
    - defaultRetention:
      - days: 5
        mode: COMPLIANCE

---

apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    meta.upbound.io/example-id: s3/v1beta1/bucketobjectlockconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    objectLockEnabled: true
    region: us-west-1

---

