# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: grafana.aws.m.upbound.io/v1beta1
kind: WorkspaceAPIKey
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Depends on resource with manual intervention."
    meta.upbound.io/example-id: grafana/v1beta1/workspaceapikey
  labels:
    testing.upbound.io/example-name: key
  name: key
spec:
  forProvider:
    keyName: test-key
    keyRole: VIEWER
    region: us-east-1
    secondsToLive: 3600
    workspaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: wstest
---
apiVersion: grafana.aws.m.upbound.io/v1beta1
kind: Workspace
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1beta1/workspaceapikey
  labels:
    testing.upbound.io/example-name: wstest
  name: wstest-${Rand.RFC1123Subdomain}
spec:
  forProvider:
    accountAccessType: CURRENT_ACCOUNT
    authenticationProviders:
      - AWS_SSO
    permissionType: SERVICE_MANAGED
    region: us-east-1
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: assume-wa
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: grafana/v1beta1/workspaceapikey
  labels:
    testing.upbound.io/example-name: assume-wa
  name: assume-wa
spec:
  forProvider:
    assumeRolePolicy: |-
      ${jsonencode({
          Version = "2012-10-17"
          Statement = [
            {
              Action = "sts:AssumeRole"
              Effect = "Allow"
              Sid    = ""
              Principal = {
                Service = "grafana.amazonaws.com"
              }
            },
          ]
        })}
