apiVersion: licensemanager.m.aws.upbound.io/v1beta1
kind: LicenseConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: licensemanager/v1beta1/licenseconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Example
    licenseCount: 10
    licenseCountHardLimit: true
    licenseCountingType: Socket
    licenseRules:
    - '#minimumSockets=2'
    name: Example
    region: us-west-1
    tags:
      foo: barr
