# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: cognitoidp.aws.upbound.io/v1beta1
kind: RiskConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: cognitoidp/v1beta1/riskconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    region: us-east-2
    riskExceptionConfiguration:
    - blockedIpRangeList:
      - 10.10.10.10/32
    userPoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: cognitoidp.aws.upbound.io/v1beta1
kind: UserPool
metadata:
  annotations:
    meta.upbound.io/example-id: cognitoidp/v1beta1/riskconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example
    passwordPolicy:
      - minimumLength: 6
        requireNumbers: false
        requireSymbols: false
        requireUppercase: false
        temporaryPasswordValidityDays: 7
    region: us-east-2
