apiVersion: imagebuilder.aws.m.upbound.io/v1beta1
kind: DistributionConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: imagebuilder/v1beta1/distributionconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    distribution:
    - amiDistributionConfiguration:
      - amiTags:
          CostCenter: IT
        launchPermission:
        - userIds:
          - "123456789012"
        name: example-{{ imagebuilder:buildDate }}
      launchTemplateConfiguration:
      - launchTemplateId: lt-0aaa1bcde2ff3456
      region: us-east-1
    name: example
    region: us-west-1
