apiVersion: apprunner.aws.upbound.io/v1alpha1
kind: AutoScalingConfigurationVersion
metadata:
  name: example
spec:
  forProvider:
    autoScalingConfigurationName: example
    maxConcurrency: 50
    maxSize: 10
    minSize: 2
    tags:
      Name: example-apprunner-autoscaling
  providerConfigRef:
    name: example
