apiVersion: emrserverless.aws.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: emrserverless/v1beta1/application
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example
    region: us-west-1
    releaseLabel: emr-6.6.0
    type: hive

---

