# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketObjectLockConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketobjectlockconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: s3
    region: us-east-2
    rule:
    - defaultRetention:
      - days: 5
        mode: COMPLIANCE
