# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketReplicationConfiguration
metadata:
  name: example
  annotations:
    upjet.upbound.io/manual-intervention: "Requires a Role with permissions on both buckets."
spec:
  forProvider:
    region: us-east-2
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: s3
    role: <role ARN>
    rule:
    - destination:
      - bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: s3
        storageClass: STANDARD
      filter:
      - prefix: foo
      id: foobar
      deleteMarkerReplication:
      - status: Enabled
      status: Enabled
