# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: glue.aws.upbound.io/v1beta1
kind: SecurityConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: glue/v1beta1/securityconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    encryptionConfiguration:
    - cloudwatchEncryption:
      - cloudwatchEncryptionMode: DISABLED
      jobBookmarksEncryption:
      - jobBookmarksEncryptionMode: DISABLED
      s3Encryption:
      - kmsKeyArnSelector:
          matchLabels:
             testing.upbound.io/example-name: glue-example-key
        s3EncryptionMode: SSE-KMS
    region: us-east-2
---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Key
metadata:
  labels:
    testing.upbound.io/example-name: glue-example-key
  name: glue-example-key
spec:
  forProvider:
    region: us-east-2
    description: Created with Crossplane
    deletionWindowInDays: 7
