apiVersion: backup.aws.upbound.io/v1beta1
kind: VaultLockConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: backup/v1beta1/vaultlockconfiguration
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    backupVaultNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    changeableForDays: 3
    maxRetentionDays: 1200
    minRetentionDays: 7
    region: us-west-1

---

