apiVersion: lambda.aws.upbound.io/v1alpha1
kind: ProvisionedConcurrencyConfig
metadata:
  name: example
spec:
  forProvider:
    functionName: ${aws_lambda_alias.example.function_name}
    provisionedConcurrentExecutions: 1
    qualifier: my_alias
  providerConfigRef:
    name: example
