apiVersion: apigateway.aws.upbound.io/v1alpha1
kind: Deployment
metadata:
  name: example
spec:
  forProvider:
    lifecycle:
    - create_before_destroy: true
    restApiId: ${aws_api_gateway_rest_api.example.id}
    triggers:
      redeployment: ${sha1(jsonencode(aws_api_gateway_rest_api.example.body))}
  providerConfigRef:
    name: example
