apiVersion: licensemanager.aws.upbound.io/v1alpha1
kind: LicenseConfiguration
metadata:
  name: example
spec:
  forProvider:
    description: Example
    licenseCount: 10
    licenseCountHardLimit: true
    licenseCountingType: Socket
    licenseRules:
    - '#minimumSockets=2'
    name: Example
    tags:
      foo: barr
  providerConfigRef:
    name: example
