# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: lakeformation.aws.upbound.io/v1beta1
kind: DataLakeSettings
metadata:
  name: example
spec:
  forProvider:
    region: us-east-2
    admins:
    - ${aws_iam_user.example.arn}
    - ${aws_iam_role.example.arn}
