apiVersion: guardduty.aws.upbound.io/v1alpha1
kind: OrganizationConfiguration
metadata:
  name: example
spec:
  forProvider:
    autoEnable: true
    datasources:
    - s3Logs:
      - autoEnable: true
    detectorId: ${aws_guardduty_detector.example.id}
  providerConfigRef:
    name: example
