# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: configservice.aws.upbound.io/v1beta1
kind: ConfigurationRecorder
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/configurationrecorder
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    region: us-east-2
    roleArnSelector:
      matchLabels:
        testing.upbound.io/example-name: r

---

apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/configurationrecorder
  labels:
    testing.upbound.io/example-name: r
  name: r
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": "sts:AssumeRole",
            "Principal": {
              "Service": "config.amazonaws.com"
            },
            "Effect": "Allow",
            "Sid": ""
          }
        ]
      }
