# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: configservice.aws.upbound.io/v1beta1
kind: ConfigurationAggregator
metadata:
  annotations:
    meta.upbound.io/example-id: configservice/v1beta1/configurationaggregator
  labels:
    testing.upbound.io/example-name: account
  name: account
spec:
  forProvider:
    accountAggregationSource:
    - accountIds:
      - "${data.aws_account_id}"
      regions:
      - us-west-2
    region: us-east-2
