# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: imagebuilder.aws.m.upbound.io/v1beta1
kind: InfrastructureConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: imagebuilder/v1beta1/infrastructureconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: example description
    instanceProfileNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: exmple
    region: us-west-1
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: InstanceProfile
metadata:
  annotations:
    meta.upbound.io/example-id: imagebuilder/v1beta1/infrastructureconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: role
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: imagebuilder/v1beta1/infrastructureconfiguration
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    assumeRolePolicy: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Action": "sts:AssumeRole",
                  "Principal": {
                     "Service": "ec2.amazonaws.com"
                  },
                  "Effect": "Allow",
                  "Sid": ""
              }
          ]
       }
