# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: imagebuilder.aws.upbound.io/v1beta2
kind: InfrastructureConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: imagebuilder/v1beta2/infrastructureconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: example description
    instanceProfileNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    instanceTypes:
    - t2.nano
    - t3.micro
    keyPairSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    logging:
      s3Logs:
        s3BucketNameSelector:
          matchLabels:
            testing.upbound.io/example-name: example
        s3KeyPrefix: logs
    name: example
    region: us-west-1
    securityGroupIdRefs:
    - name: example
    snsTopicArnSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: main
    tags:
      foo: bar
    terminateInstanceOnFailure: true
