# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

name: Issue Triage

on:
  issues:
    types:
      - opened
      - unlabeled

jobs:
  community-issue-triage:
    uses: upbound/uptest/.github/workflows/issue-triage.yml@standard-runners
    secrets:
      UPBOUND_BOT_GITHUB_TOKEN: ${{ secrets.UPBOUND_COMMUNITY_BOT_GITHUB_TOKEN }}
