name: Native Provider Version Bump

on:
  workflow_dispatch: {}

jobs:
  open-bump-pr:
    uses: upbound/uptest/.github/workflows/native-provider-bump.yml@main
    with:
      provider-source: hashicorp/aws
      go-version: 1.19
    secrets:
      TOKEN: ${{ secrets.OFFICIAL_PROVIDERS_GA_TOKEN }}
