# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

name: Native Provider Version Bump

on:
  workflow_dispatch: {}

jobs:
  open-bump-pr:
    uses: upbound/official-providers-ci/.github/workflows/native-provider-bump.yml@standard-runners
    with:
      provider-source: hashicorp/aws
      go-version: 1.21
    secrets:
      TOKEN: ${{ secrets.OFFICIAL_PROVIDERS_GA_TOKEN }}
