name: Pull Request Triage

on:
  pull_request:
    types:
      - opened
      - unlabeled

jobs:
  community-pr-triage:
    uses: upbound/uptest/.github/workflows/pr-triage.yml@main
    secrets:
      UPBOUND_BOT_GITHUB_TOKEN: ${{ secrets.UPBOUND_BOT_GITHUB_TOKEN }}
