name: Publish Service Artifacts

on:
  workflow_dispatch: 
    inputs:
      subpackages:
        description: 'Subpackages to be built individually (e.g. monolith config ec2)'
        default: 'monolith'
        required: false
      size:
        description: "Number of smaller provider packages to build and push with each build job"
        default: '30'
        required: true
      concurrency:
        description: "Number of parallel package builds within each build job"
        default: '1'
        required: false
      regorg:
        description: 'Package registry and organization where the packages will be pushed or (e.g. xpkg.upbound.io/upbound)'
        default: 'xpkg.upbound.io/upbound'
        required: false
      branch_name:
        description: "Branch name to use while publishing the packages (e.g. main)"
        default: ''
        required: false
      version:
        description: "Version string to use while publishing the packages (e.g. v1.0.0-alpha.1)"
        default: ''
        required: false

jobs:
  publish-service-artifacts:
    uses: upbound/uptest/.github/workflows/provider-publish-service-artifacts.yml@standard-runners
    with:
      subpackages: ${{ github.event.inputs.subpackages }}
      size: ${{ github.event.inputs.size }}
      concurrency: ${{ github.event.inputs.concurrency }}
      regorg: ${{ github.event.inputs.regorg }}
      branch_name: ${{ github.event.inputs.branch_name }}
      version: ${{ github.event.inputs.version }}
      go-version: 1.21
      cleanup-disk: true
    secrets:
      UPBOUND_MARKETPLACE_PUSH_ROBOT_USR: ${{ secrets.UPBOUND_MARKETPLACE_PUSH_ROBOT_USR_RC }}
      UPBOUND_MARKETPLACE_PUSH_ROBOT_PSW: ${{ secrets.UPBOUND_MARKETPLACE_PUSH_ROBOT_PSW_RC }}
