name: Publish Service Artifacts

on:
  workflow_dispatch: 
    inputs:
      subpackages:
        description: 'Subpackages to be built individually (e.g. monolith config ec2)'
        default: 'monolith'
        required: false
      version:
        description: 'Provider version (e.g. v0.1.0)'
        required: true
      size:
        description: "Number of smaller provider packages to build and push with each build job"
        default: '30'
        required: true
      concurrency:
        description: "Number of parallel package builds within each build job"
        default: '1'
        required: false

jobs:
  publish-service-artifacts:
    uses: upbound/uptest/.github/workflows/provider-publish-service-artifacts.yml@main
    with:
      subpackages: ${{ github.event.inputs.subpackages }}
      version: ${{ github.event.inputs.version }}
      size: ${{ github.event.inputs.size }}
      concurrency: ${{ github.event.inputs.concurrency }}
    secrets:
      UPBOUND_MARKETPLACE_PUSH_ROBOT_USR: ${{ secrets.UPBOUND_MARKETPLACE_PUSH_ROBOT_USR_RC }}
      UPBOUND_MARKETPLACE_PUSH_ROBOT_PSW: ${{ secrets.UPBOUND_MARKETPLACE_PUSH_ROBOT_PSW_RC }}
