name: Uptest All

on:
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.19'
  DOCKER_BUILDX_VERSION: 'v0.8.2'

jobs:
  detect-api-groups:
    runs-on: ubuntu-22.04
    outputs:
      api_groups: ${{ steps.api-groups.outputs.list }}
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          submodules: true
      - name: Detect Api Groups
        id: api-groups
        run: |
          export API_GROUPS=""
          for i in $(ls -d examples/*/); do API_GROUPS="${API_GROUPS},${i}"; done
          
          OUTPUT=$(python3 -c "\
          import os, sys; \
          value = os.getenv('API_GROUPS'); \
          list = value.split(','); \
          print(list[1:]); \
          ")
          echo "Api Groups: $OUTPUT"
          echo "list=${OUTPUT}" >> $GITHUB_OUTPUT

  uptest:
    runs-on: ubuntu-22.04
    needs: detect-api-groups
    strategy:
      fail-fast: false
      matrix:
        api-groups: ${{ fromJson(needs.detect-api-groups.outputs.api_groups) }}
        exclude:
          - api-groups: examples/providerconfig/
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2
        with:
          platforms: all

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@16c0bc4a6e6ada2cfd8afd41d22d95379cf7c32a # v2
        with:
          version: ${{ env.DOCKER_BUILDX_VERSION }}
          install: true

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Setup Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Find the Go Build Cache
        id: go
        run: echo "cache=$(go env GOCACHE)" >> $GITHUB_OUTPUT

      - name: Cache the Go Build Cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: ${{ steps.go.outputs.cache }}
          key: ${{ runner.os }}-build-uptest-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-build-uptest-

      - name: Cache Go Dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: .work/pkg
          key: ${{ runner.os }}-pkg-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-pkg-

      - name: Vendor Dependencies
        run: make vendor vendor.check

      - name: Build Artifacts
        run: make -j2 build.all
        env:
          # We're using docker buildx, which doesn't actually load the images it
          # builds by default. Specifying --load does so.
          BUILD_ARGS: "--load"

      - name: Prepare The Example List
        id: prepare-example-list
        run: |
          cd ..
          EXAMPLE_LIST=""
          EXAMPLE_LIST="${EXAMPLE_LIST},$(find ${{ matrix.api-groups }} -name '*.yaml' | tr '\n' ',')"
          echo "example-list=${EXAMPLE_LIST:1}" >> $GITHUB_OUTPUT
          echo "Examples: ${EXAMPLE_LIST:1}"

      - name: Run Uptest
        id: run-uptest
        env:
          UPTEST_AWS_CREDS: ${{ secrets.UPTEST_AWS_CREDS }}
          EXAMPLE_LIST: ${{ needs.get-example-list.outputs.example_list }}
          UPTEST_EXAMPLE_VALUE_REPLACEMENTS: ${{ secrets.UPTEST_EXAMPLE_VALUE_REPLACEMENTS }}
          DUMP_DIRECTORY: "./_output/cluster-dump"
        run: make uptest

      - name: Collect Cluster Dump
        if: always()
        run: |
          export DUMP_DIRECTORY=./_output/cluster-dump
          make cluster_dump

      - name: Upload Cluster Dump
        if: always()
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: cluster-dump-aws
          path: ./_output/cluster-dump

      - name: Cleanup
        if: always()
        run: |
          kubectl delete managed --all

  report:
    runs-on: ubuntu-22.04
    needs: uptest
    if: always()
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          submodules: true
      - name: Manual Intervention Report
        run: |
          echo "Total Resources for AWS: $(cat examples/*/* | grep -o "kind: " | wc -l)"
          echo "Number of Skipped Resources: $(grep -r -o "upjet.upbound.io/manual-intervention" examples/* | wc -l)"
          echo "Skipped Manifests (Manual Intervention): $(grep -r -o "upjet.upbound.io/manual-intervention" examples/*)"
      - name: Coverage Report
        run: |
          OUTPUT=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs | jq '.jobs | .[] | select(.name!="detect-api-groups" and .name!="report")  | .name + " -> " + .conclusion')
          FAILURE=$(echo ${OUTPUT} | grep -o 'failure' | wc -l)
          SUCCESS=$(echo ${OUTPUT} | grep -o 'success' | wc -l)
          echo "Success: ${SUCCESS}"
          echo "Failure: ${FAILURE}" 
          echo "${OUTPUT}"
