apiVersion: kinesisanalyticsv2.m.aws.upbound.io/v1beta1
kind: ApplicationSnapshot
metadata:
  annotations:
    meta.upbound.io/example-id: kinesisanalyticsv2/v1beta1/applicationsnapshot
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    applicationNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    region: us-west-1
