# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: kinesisanalyticsv2.aws.m.upbound.io/v1beta1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: kinesisanalyticsv2/v1beta1/application
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    applicationConfiguration:
      applicationCodeConfiguration:
        codeContent:
          s3ContentLocation:
            bucketArnSelector:
              matchLabels:
                testing.upbound.io/example-name: example
            fileKeySelector:
              matchLabels:
                testing.upbound.io/example-name: example
        codeContentType: ZIPFILE
      environmentProperties:
        propertyGroup:
        - propertyGroupId: PROPERTY-GROUP-1
          propertyMap:
            Key1: Value1
        - propertyGroupId: PROPERTY-GROUP-2
          propertyMap:
            KeyA: ValueA
            KeyB: ValueB
      flinkApplicationConfiguration:
        checkpointConfiguration:
          configurationType: DEFAULT
        monitoringConfiguration:
          configurationType: CUSTOM
          logLevel: DEBUG
          metricsLevel: TASK
        parallelismConfiguration:
          autoScalingEnabled: true
          configurationType: CUSTOM
          parallelism: 10
          parallelismPerKpu: 4
    region: us-west-1
    runtimeEnvironment: FLINK-1_8
    serviceExecutionRoleSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    tags:
      Environment: test

---

apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    meta.upbound.io/example-id: kinesisanalyticsv2/v1beta1/application
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    region: us-west-1

---

apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Object
metadata:
  annotations:
    meta.upbound.io/example-id: kinesisanalyticsv2/v1beta1/application
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    key: example-flink-application
    region: us-west-1
    source: flink-app.jar
