apiVersion: lambda.aws.m.upbound.io/v1beta1
kind: CodeSigningConfig
metadata:
  annotations:
    meta.upbound.io/example-id: lambda/v1beta1/codesigningconfig
  labels:
    testing.upbound.io/example-name: new_csc
  name: new-csc
spec:
  forProvider:
    allowedPublishers:
    - signingProfileVersionArnsRefs:
      - name: example1
      - name: example2
    description: My awesome code signing config.
    policies:
    - untrustedArtifactOnDeployment: Warn
    region: us-west-1
    tags:
      Name: dynamodb
