apiVersion: lambda.aws.m.upbound.io/v1beta1
kind: ProvisionedConcurrencyConfig
metadata:
  annotations:
    meta.upbound.io/example-id: lambda/v1beta1/provisionedconcurrencyconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    functionName: ${aws_lambda_alias.example.function_name}
    provisionedConcurrentExecutions: 1
    qualifier: ${aws_lambda_alias.example.name}
    region: us-west-1
