# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: mq.aws.m.upbound.io/v1beta1
kind: Configuration
metadata:
  name: example
  namespace: upbound-system
spec:
  forProvider:
    # Due to an existing Terrajet limitation, we cannot use "metadata.name" for "name"
    # Details can be found in https://github.com/crossplane/terrajet/issues/280
    name: example-config
    region: us-west-1
    data: |
      <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
      <broker xmlns="http://activemq.apache.org/schema/core">
        <plugins>
          <forcePersistencyModeBrokerPlugin persistenceFlag="true"/>
          <statisticsBrokerPlugin/>
          <timeStampingBrokerPlugin ttlCeiling="86400000" zeroExpirationOverride="86400000"/>
        </plugins>
      </broker>
    description: Example Configuration
    engineType: ActiveMQ
    engineVersion: "5.18"
