apiVersion: eks.aws.m.upbound.io/v1beta1
kind: IdentityProviderConfig
metadata:
  annotations:
    meta.upbound.io/example-id: eks/v1beta1/identityproviderconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    clusterNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    oidc:
    - clientId: your client_id
      issuerUrl: your issuer_url
    region: us-west-1
